In [1]:
import numpy as np

In [3]:
arr1= np.zeros(3)
arr1

array([0., 0., 0.])

In [11]:
arr2D= np.array([
    
     [ 
         [2,3,4],[2,7,4]
     ],
    
    
    [
        [2,3,2],[5,2,5]
    ],
    
    [
        [3,2,4],[2,5,2]
    ]
])
arr2D.shape

arr2= np.array([[[2,3,4],[5,6,7],[8,9,10]]])
arr2.ndim

3

### Learning about dimensions arrays in numpy

In [13]:
arr3= np.array([
    [
        [2,4,5,3,1,8,6,2],
        [4,7,4,5,7,3,4,5]
    ]
])
arr3.shape

(1, 2, 8)

In [26]:
arr4= arr3.reshape(2,2,4)
print(arr4)

[[[2 4 5 3]
  [1 8 6 2]]

 [[4 7 4 5]
  [7 3 4 5]]]


### Shape -> (2,2,4) meaning
#### one big threeD array, this big 3D array contains 2, twoD array (i.e. two rows)
####  and each of these twoD array contains 4 elements in each

In [25]:
arr4.flatten()

array([2, 4, 5, 3, 1, 8, 6, 2, 4, 7, 4, 5, 7, 3, 4, 5])