<center><h2>computer vision domain</h2><center>

In [1]:
import cv2 as cv  #Importing opencv 

In [28]:
#How to verify if opencv is installed properly
img = cv.imread("Grouppic.jpg")  #Reading the image
cv.imshow("Display window", img)  
cv.waitKey(0)
cv.destroyAllWindows()

In [3]:
img

array([[[144, 137, 144],
        [144, 137, 144],
        [144, 137, 144],
        ...,
        [179, 160, 147],
        [176, 160, 147],
        [176, 160, 148]],

       [[145, 138, 145],
        [144, 137, 144],
        [144, 137, 144],
        ...,
        [179, 160, 147],
        [176, 160, 147],
        [176, 160, 148]],

       [[145, 138, 145],
        [145, 138, 145],
        [145, 138, 145],
        ...,
        [179, 160, 147],
        [176, 160, 147],
        [176, 160, 148]],

       ...,

       [[ 13,  13,  13],
        [ 14,  14,  14],
        [ 14,  14,  14],
        ...,
        [125, 148, 150],
        [128, 149, 151],
        [130, 149, 152]],

       [[ 14,  14,  14],
        [ 14,  14,  14],
        [ 14,  14,  14],
        ...,
        [127, 148, 150],
        [129, 148, 151],
        [132, 149, 152]],

       [[ 14,  14,  14],
        [ 14,  14,  14],
        [ 15,  15,  15],
        ...,
        [128, 147, 150],
        [131, 148, 151],
        [134, 149, 152]]

In [4]:
img.shape

(701, 1163, 3)

In [29]:
gray_image= cv.cvtColor(img, cv.COLOR_BGR2GRAY)   # Converting to grayscale 

In [6]:
gray_image

array([[140, 140, 140, ..., 158, 158, 158],
       [141, 140, 140, ..., 158, 158, 158],
       [141, 141, 141, ..., 158, 158, 158],
       ...,
       [ 13,  14,  14, ..., 146, 147, 148],
       [ 14,  14,  14, ..., 146, 147, 148],
       [ 14,  14,  15, ..., 146, 147, 148]], dtype=uint8)

In [ ]:
cv.imshow("Display window", gray_image)  
cv.waitKey(0)
cv.destroyAllWindows()

In [8]:
face_classifier = cv.CascadeClassifier(
cv.data.haarcascades+"haarcascade_frontalface_default.xml"
)

In [47]:
face = face_classifier.detectMultiScale(
gray_image, scaleFactor= 1.1, minNeighbors= 5, minSize=(40,40)
)

In [48]:
print(face)

[[916 269 100 100]
 [802 375 101 101]]


In [49]:
#Lets perform face detection

In [50]:
for (x,y,w,h) in face:
    cv.rectangle(img, (x,y), (x+w, y+h),(0,255,0),4)

In [51]:
img_rgb= cv.cvtColor(img, cv.COLOR_BGR2RGB)

In [52]:
cv.imshow("Display window", img_rgb)  
cv.waitKey(0)
cv.destroyAllWindows()

## Detecting Face from video

In [1]:
import cv2 as cv

In [2]:
face_classifier = cv.CascadeClassifier(
cv.data.haarcascades+"haarcascade_frontalface_default.xml"
)

In [3]:
#Access the Webcame

In [4]:
video_capture = cv.VideoCapture(0)

In [5]:
def detect_bounding_box(vid):
    gray_image = cv.cvtColor(vid, cv.COLOR_BGR2GRAY)
    faces= face_classifier.detectMultiScale(gray_image, 1.1, 5, minSize=(40,40))
    for(x,y,w,h) in faces:
        cv.rectangle(vid, (x,y), (x+w, y+h), (0,255,0),4)
        return faces

In [6]:
while True:
    result, video_frame = video_capture.read()
    if result is False:
        break
    
    faces = detect_bounding_box(
    video_frame
    )
    
    cv.imshow(
    "My Face Detection Project", video_frame
    )
    
    if cv.waitKey(1) & 0xFF == ord("q"):
        break
video_capture.release()
#cv.waitKey(0)
cv.destroyAllWindows()

# From photo

In [7]:
import cv2 as cv
import numpy as np

def upload_and_recognize():
    """
    Function to upload a photo, detect faces, and display the image with recognized faces highlighted.

    Returns:
        None
    """
    # Upload a photo
    img_path = input("Enter the path of the image file: ")
    img = cv.imread(img_path)

    # Check if the image is loaded successfully
    if img is None:
        print("Error: Unable to load the image.")
        return

    # Display the original image
    cv.imshow("Original Image", img)
    cv.waitKey(0)

    # Convert the image to grayscale
    gray_image = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

    # Load the pre-trained face cascade classifier
    face_cascade = cv.CascadeClassifier(cv.data.haarcascades + "haarcascade_frontalface_default.xml")

    # Detect faces in the grayscale image
    faces = face_cascade.detectMultiScale(gray_image, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

    # Draw rectangles around the detected faces and display the image
    for (x, y, w, h) in faces:
        cv.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)

    # Display the image with detected faces
    cv.imshow("Detected Faces", img)
    cv.waitKey(0)

    # Close all OpenCV windows
    cv.destroyAllWindows()

# Call the function to upload and recognize faces in the photo
upload_and_recognize()


Enter the path of the image file: C:\Users\rocke\Favorites\Python Bootcamp\Day 8\Grouppic.jpg
